export const PHASE4_GAMEPLAY_CONFIG = Object.freeze({
  launch: Object.freeze({
    thresholdSpeed: 1.2,
    // Continuous V9 launch: exactly zero at threshold, then eased upward.
    visiblePopVelocity: 0,
    speedForMaximumVelocity: 22,
    maximumVerticalVelocity: 27,
  }),
  gravity: Object.freeze({
    downhillScale: 1.08,
    uphillScale: 1.35,
  }),
  pumping: Object.freeze({
    acceleration: 16.0,
    inputBufferSeconds: 0.15,
    wrongPenaltyAcceleration: 0.9,
    ratingMultipliers: Object.freeze({
      PERFECT: 1.0,
      GOOD: 0.90,
      WEAK: 0.65,
      EARLY: 0.32,
      LATE: 0.32,
      WRONG: -0.35,
    }),
    rhythmBoostPerfect: 0.027,
    rhythmBoostGood: 0.016,
    rhythmBoostWeak: 0.0055,
    rhythmBoostPenalty: 0.02,
    rhythmBoostMax: 0.085,
    lowEnergyRecovery: Object.freeze({
      // All recovery work requires a correctly directed player pump. Budget
      // the extra kinetic energy per surface phase, not per button press.
      referenceSpeed: 10.0,
      minimumSpeed: 0,
      minRecoverableSpeed: 0.35,
      acceleration: 9.0,
      lowSpeedPumpMultiplier: 1.65,
      maxPumpBonus: 9.0,
      maxWindowWork: 42.0,
      pumpCooldownSeconds: 0.32,
      rewardTargetSpeed: 13.0,
      minimumImpulseScale: 0.35,
      attemptImpulseByRating: Object.freeze({
        PERFECT: 2.1,
        GOOD: 1.5,
        WEAK: 0.65,
        EARLY: 0.75,
        LATE: 0.75,
        WRONG: 0,
      }),
      eligibleRatings: Object.freeze(['PERFECT', 'GOOD', 'WEAK', 'EARLY', 'LATE']),
    }),
  }),
  aerial: Object.freeze({
    // V14 deliberately slows aerial turning and caps the highest valid turn at
    // 720. The 720 remains achievable on a maximum-energy launch, but 900 is
    // no longer a valid or reachable scored target.
    rotationDegreesPerSecond: 600,
    v9RotationDegreesPerSecond: 720,
    targetStepDegrees: 180,
    maximumDegrees: 720,
    validErrorDegrees: 48,
    hardOverrunDegrees: 72,
    idealErrorDegrees: 12,
    validMinDegrees: 132,
    idealMinDegrees: 168,
    idealMaxDegrees: 192,
    validMaxDegrees: 228,
    overturnDegrees: 792,
  }),
  backflip: Object.freeze({
    rotationDegreesPerSecond: 500,
    v9RotationDegreesPerSecond: 720,
    singleDegrees: 360,
    doubleDegrees: 720,
    validErrorDegrees: 42,
    hardOverrunDegrees: 66,
    doubleMinimumLaunchVelocity: 22,
  }),
  landing: Object.freeze({
    activeSeconds: 0.28,
    impactPerfectMax: 24,
    impactCleanMax: 40,
    impactSketchyMax: 46,
    impactHeavyMax: 52,
    rotationPerfectError: 14,
    rotationCleanError: 28,
    rotationSketchyError: 42,
    rotationHeavyError: 58,
  }),
  crash: Object.freeze({
    recoverySeconds: 0.28,
    bailMomentumRetention: 0.8,
    pumpLockSeconds: 0,
    recoveryPumpAccelerationMultiplier: 1,
    recoveryMinimumPumpMultiplier: 1,
    recoveryWrongPumpPenaltyMultiplier: 1,
    recoveryPumpMinimumSpeed: 0.20,
    technicalBounceSpeed: 2.4,
  }),
  surfaceTricks: Object.freeze({
    handPlantEligibilityFraction: 0.955,
    handPlantInputBufferSeconds: 0.32,
    handPlantMaxCopingDistance: 0.27,
    handPlantMinimumEntrySpeed: 0.4,
    handPlantMinimumHoldSeconds: 1 / 120,
    handPlantIdealHoldSeconds: 0.28,
    handPlantMaximumQualityHoldSeconds: 0.52,
    kickTurnBufferSeconds: 0.13,
  }),
});
