export const GAME_CONFIG = Object.freeze({
  assets: Object.freeze({
    halfpipe: '/models/halfpipe/halfpipe.glb',
    skateboard: '/models/skateboard/skateboard.glb',
    chimpion: '/models/characters/The%20Heretic.glb',
    background: '/images/backgrounds/halfpipe-hollywood-original.jpg',
  }),
  renderer: Object.freeze({
    maxPixelRatio: 2,
    clearColor: 0x000000,
    shadowMapSize: 2048,
  }),
  skateboard: Object.freeze({
    scale: 0.095,
    wheelRadius: 0.036,
    surfaceClearance: 0.18,
  }),
  rider: Object.freeze({
    targetHeight: 2.15,
    deckClearance: 0.025,
    stance: 'regular',
    stanceHalfLength: 0.24,
    footLateralOffset: 0.015,
  }),
  halfpipeProfile: Object.freeze({
    flatHalfWidth: 2.35,
    transitionWidth: 5.62,
    transitionHeight: 6.62,
    debugDepth: 8.3,
    debugVisible: false,
  }),
  passivePhysics: Object.freeze({
    fixedHz: 120,
    gravity: 52,
    linearDrag: 0.035,
    maxFrameDelta: 0.1,
    maxSubSteps: 20,
    lipInset: 0.002,
    velocityEpsilon: 0.0001,
    startTransitionFraction: 0.72,
    initialVelocity: 0,
    presentationSpeedReference: 17,
    presentationVerticalEpsilon: 0.02,
  }),
  session: Object.freeze({
    durationSeconds: 75,
  }),
  arcadeMotion: Object.freeze({
    downhillGravityScale: 1.12,
    uphillGravityScale: 1.6,
  }),
  pumping: Object.freeze({
    acceleration: 8.5,
    upperWallRetention: 0.62,
    minimumSpeed: 0.65,
  }),
  turning: Object.freeze({
    kickTurnMinFraction: 0.72,
    kickTurnRetention: 0.93,
    handPlantMinFraction: 0.92,
    handPlantRetention: 0.9,
    aerialIdealHoldSeconds: 0.2,
    aerialCompleteSeconds: 0.14,
    aerialOverturnSeconds: 0.5,
  }),
  scoring: Object.freeze({
    kickTurn: Object.freeze({ min: 100, max: 300 }),
    handPlant: Object.freeze({ min: 400, max: 700 }),
    aerialTurn: Object.freeze({ min: 400, max: 999 }),
  }),
  trickPresentation: Object.freeze({
    kickTurnDuration: 0.38,
    handPlantDuration: 0.52,
    kickTurnLift: 0.12,
    kickTurnRoll: 0.16,
    handPlantLift: 0.28,
    handPlantShift: 0.18,
    handPlantRoll: 1.18,
    aerialRoll: 0.2,
  }),
  air: Object.freeze({
    takeoffInset: 0.005,
    launchMinimumSpeed: 1.2,
    minimumVerticalVelocity: 10,
    maximumVerticalVelocity: 20,
    gravity: 50,
    launchVelocityScale: 1.18,
    landingVelocityRetention: 0.94,
  }),
  camera: Object.freeze({
    fov: 30,
    near: 0.1,
    far: 180,
    position: Object.freeze([0, 6.0, 24.5]),
    target: Object.freeze([0, 3.9, 0]),
    dynamicAirFraming: Object.freeze({
      enterHeight: 7.6,
      exitHeight: 7.0,
      maxTrackedHeight: 10.5,
      maxFov: 38,
      maxTargetY: 6.6,
      response: 5.5,
    }),
  }),
});
